### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by iiBlake** [RainbowDinoaur/Discorddit-Webhook#1]
Got a random error:

Traceback (most recent call last):
  File "main.py", line 150, in <module>
    post(data[i], url, img, colour)
  File "main.py", line 126, in post
    print("Posted "+data["data"]["title"])
  File "C:\Users\blake\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 57-58: character maps to <undefined>

**Comment by RainbowDinoaur** [comment]
Fixed. Should of got it sooner sorry for the wait. Just over looked unicode literals. It will now print out the code for the character and not the character itself so that it doesn't break when using Windows. Do message me again if this doesn't solve your issue.
